### PR TITLE
API Changes (Including refactoring in project).

### PR DESCRIPTION
**Pull request by Azoraqua**
* Added `createIsland()` to uSkyBlockAPI interface (As @rlf (You) noticed).
* Refactored `getHasIsland()` to `hasIsland()` in whole project (I made sure all references are replaced).

### CODE REVIEW

**Comment by jesseke55** [comment]
+1

**Comment by rlf** [comment]
Declining.
# don't use * imports (makes merging harder).
# if you add `createIsland`, we need to maake sure allways to fire the event. Even if it`s fired as cancelled, so plugins can know if it was a success or not.

**Comment by Azoraqua** [comment]
@rlf Sorry, IntelliJ automatically changes imports from the same packages to `<package>.*`.
Also I'll try to fix the event system about it.

**Comment by rlf** [comment]
On second thought dont mess with the event. If the create fails, its just too bad.
You can disable star imports in IDEA.

**Comment by Azoraqua** [comment]
Let's ask you, if I get to fix the event system, We use a `beta` branch okay, then are bugs 'okay'?

**Comment by rlf** [comment]
No. Just stabilize on your own fork.
Make a pull request when it has been tested and is ready.

**Comment by Azoraqua** [comment]
Okay, sir @rlf .

**Pull request closed without merging**
