### PR TITLE
Fix maxPartySize in the config being ignored.

### PR DESCRIPTION
**Pull request by Harry5573**
This fixes maxPartySize in the config being ignored, since right now if
you generate an island without any of the extra perms it will default to
4 max members instead of what is set in the config.

This also removes the party.yml and the player.yml which are not used.

It also removes the redundant max party size check in the home command
which breaks the permissions for having more party members.

### CODE REVIEW

**Comment by rlf** [comment]
Great! Nice to have someone else contributing.
Just a note, the reason the "config-override" was in there (and I think it needs to get in there again), is to allow for "Old-islands" to benefit from a "global" change of the max party size.
I think that needs to be kept in there?

**Comment by rlf** [comment]
Actually, your change will break the "maxPartySize" for trusted players.

Let me explain.
What happens is, one (or more players) on an island buys some VIP access, and get a permission allowing for more island-members.

This is then active for the whole island - also for other members joining the island.
Your change will force the global value, regardless of whether the island has had it's max increased by a VIP member.

**Comment by dutchy1001** [comment]
I think I've send you a skype request, if not can you message me plz

**Comment by Harry5573** [comment]
@dutchy1001 I don't think i got your request, my name on skype is "harry.devane".

**Comment by Harry5573** [comment]
@rlf https://github.com/Harry5573/uSkyBlock/commit/1c867e314285ed2fe685bdaf7f034efafcb154b4, i have converted this to a dynamic system which should fix both the problems you listed above.

**Comment by rlf** [comment]
Yup, that is better.
Good job.

**Comment by Xanthus13** [comment]
So, is this change in the 2.3-HF7a version?  Ultimate-mc-net reset skyblock last night and we are running the 2.3-HF7a version and our extra party size perms are no longer working.  The config.yml has maxPartySize: 4, and my island file has maxPartySizePermission: 8, but my island shows 4/4 members and won't let me invite another member.  I have the usb.extra.party4 permission.

**Pull request merged**
