### PR TITLE
Sky Map Feature

### PR DESCRIPTION
**Pull request by asleeponduty**
Hello
Myself and a friend have been working on adding a 'Sky Map' for some time, and have reached a state where we're happy with it and believe we've nailed down most bugs. 
The sky map is a chest inventory with scrollbars. It is used for both initial island selection and as a teleportation map for traveling between islands. 
Screenshot on Imgur
The above screenshot shows the map, scrolled. 
This map is similar during island creation, however valid island locations are represented by dirt blocks rather than the glass pane background seen here. 
The compass re-centers the map on Spawn, and the sapling returns to the regular Island Menu. 
Spawn (not visible above) is represented by a bedrock block. Clicking it is the equivalent of running `/is spawn`.

This PR also contains the following notable differences:
- POM: 
  - Added the new bStats repo, and bumped the dependent version. 
  - Updated all POMs to follow the Maven spec. We were having build issues on the latest versions of Maven.
- Nether Islands:
  - Increased the WorldGuard nether region to go from 0-255, to encourage late game escapes to the roof. Teleport prevention behavior is unchanged.
  - You'll also see a commit where we added a config setting to remove the extra nether ceiling. That has since been obsoleted and no longer exists.
- Player UUIDs: Changed many calls to use player UUIDs instead of using the deprecated string name
- 'hasPermission(' deprecation: Removed calls to this, used the current methods.
- Config.yml: Three members were renamed and adjusted to make these less confusing, and their corresponding descriptions were made more clear. 
  - options.general.spawnSize is now spawnRadius
  - options.island.distance is now islandRadius (distance/2)
  - options.island.protectionRange is now protectionRadius
(protectionRange/2)

Edit: 
I would like to add and make it clear that this is building on the bleeding edge versions of WorldGuard and WorldEdit. If Sk89q decides more heavy refactoring is going to happen, we're at his mercy.

### CODE REVIEW

**Comment by asleeponduty** [comment]
I realize now that we have some changes to our version of Readme.md that specify our fork is a dev fork.
If this is to be accepted, this will have to be changed. 
Apologies in advance

**Comment by BlackBeltPanda** [comment]
Can you add a config option to disable the GUI for servers that don't want to use it? Also one to disable displaying the GUI on island creation, for servers that have their own GUI for that?

**Comment by Muspah** [comment]
It's absolutely a nice-to-have feature, you've got my +1 for the idea, but I can think of it's disadvantages for some servers too. Having two config options to disable the map entirely and disabling only the selection screen on island creation would be nice. I'm not a big fan of forcing changes like this to users without having an option to disable them. Servers that don't want the new features are going to change plugins or, maybe even worse, use old versions and expecting support ;)

**Comment by asleeponduty** [comment]
Absolutely.
I'll submit a cleaned up PR when I finish+test this.

**Comment by asleeponduty** [comment]
> 
> 
> It's absolutely a nice-to-have feature, you've got my +1 for pulling it, but I can think of it's disadvantages for some servers too. Having two config options to disable the map entirely and disabling only the selection screen on island creation would be nice. I'm not a big fan of forcing changes like this to users without having an option to disable them. Servers that don't want the new features are going to change plugins or, maybe even worse, use old versions and expecting support ;)

Expect a PR with this today

**Pull request closed without merging**
