### PR TITLE
Fixes for 1.14

### PR DESCRIPTION
**Pull request by ThexXTURBOXx**
Improved version of #1173, without using any dependency at all.
Will add more fixes eventually.
If you have any further improvements, problems or anything else, feel free to ask and I will try my best to fix that.
This PR should remain compatibility with 1.13 (not tested, but I am pretty sure)

### CODE REVIEW

**Comment by Muspah** [comment]
Thank you very much for the PR! I'll review and merge after the weekend, it's a busy one over here ;)

**Comment by ThexXTURBOXx** [comment]
No problem! I definetly understand that as a student myself, so take your time :D

**Comment by Muspah** [comment]
Hmm, student life is about 10 years ago and I can sure feel the difference on monday morning, lol 🍷 

I've checked both this PR and #1173. It's nothing personal, but I'm not a big fan of relaying on external dependencies when we can handle things in uSkyBlock itself with a limited amount of (extra) work. It usually creates more work on the long term when dependencies get abandoned and we need to switch again.

So, I'll squash and merge this PR into a Bukkit114 branch to give us a little bit of time to do some testing. Thanks again to both you and Speentie for opening a PR and taking the time to contribute to uSkyBlock!

**Comment by ThexXTURBOXx** [comment]
Oh okay, I think, I will understand that one at some point in the future, lol.

Yeah, I can definetly understand that! It's not only you, I know many people "complaining" about such things, that's why I try to help those.

Very nice and no problem, m8! Good luck in further developing. I have been a fan of uSkyBlock for a long time now, so please keep up the great work! ;)

**Pull request merged**
