### PR TITLE
Avoid "deleting" players on Island Restart and Fix #858

### LINKED ISSUE #858: obsidian to lava bucket glitch
_Please paste the output from `/usb version` below_

```
Console : [15:52:44 INFO]: Name: uSkyBlock
Console : [15:52:44 INFO]: Version: 2.7.2
Console : [15:52:44 INFO]: Description: Ultimate SkyBlock v2.7.2-45f756-430
Console : [15:52:44 INFO]: Language: en (en)
Console : [15:52:44 INFO]:   State: d=149, r=62, i=18, p=21, n=false, awe=true
Console : [15:52:44 INFO]: Server: CraftBukkit git-Spigot-90f61bc-5e5cf84 (MC: 1.10.2)
Console : [15:52:44 INFO]:   State: online=false, bungee=true
Console : [15:52:44 INFO]: ------------------------------
Console : [15:52:44 INFO]: Vault 1.5.6-b49 (ENABLED)
Console : [15:52:44 INFO]: WorldEdit 6.1.3;7a097ca (ENABLED)
Console : [15:52:44 INFO]: WorldGuard 6.1.2;e38d98d (ENABLED)
Console : [15:52:44 INFO]: AsyncWorldEdit 3.4.1 (ENABLED)
Console : [15:52:44 INFO]: Multiverse-Core 2.5-b717 (ENABLED)
Console : [15:52:44 INFO]: Multiverse-NetherPortals 2.5.0-SNAPSHOT-b712 (ENABLED)
Console : [15:52:44 INFO]: ------------------------------
```

_What steps will reproduce the problem?_ - First glitch
1. have more than one empty bucket in your inventory in different inventory slots
2. right click obsidian to turn it into a lava bucket
3. all empty buckets in your inventory that are in different slots disappear, and you get one lava bucket

_What steps will reproduce the problem?_ - Second glitch
1. have a stack of at least two buckets in your inventory
2. right click obsidian to turn it into a lava bucket
3. your stack of buckets stays the same, and you are given a lava bucket

Both of these are obviously problems as the first is deleting your buckets, and the first one is spawning you a free bucket.

Thanks :)

### PR DESCRIPTION
**Pull request by BlackBeltPanda**
In the rare case of a player being in an island region while it's cleared, they'll end up being "deleted". This causes their client to desync from the server and they're unable to chat or use commands until they relog.

Also added a fix for buckets duplicating or being lost when retrieving lava from obsidian: https://github.com/rlf/uSkyBlock/issues/858

### CODE REVIEW

**Comment by BlackBeltPanda** [comment]
Not used to working with Git, lol.

**Comment by BlackBeltPanda** [comment]
Crap, this isn't working right. >.<

**Comment by rlf** [comment]
This is probably introduced with the fix where we actively try to delete all entities when deleting an island.

See https://github.com/rlf/uSkyBlock/blob/master/uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/handler/WorldEditHandler.java#L333 and https://github.com/rlf/uSkyBlock/blob/master/uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/handler/WorldEditHandler.java#L340

Just omit player entities from that list...

**Comment by BlackBeltPanda** [comment]
Yeah, I couldn't get uSkyBlock imported properly into Eclipse. >.<

**Pull request closed without merging**
