### PR TITLE
OK, here is 2.6.0 ko.po FIle

### PR DESCRIPTION
**Pull request by swan201**
Still need to check many  format error, but you help some my jobs. :+1: thank you.

### CODE REVIEW

**Comment by rlf** [comment]
Pro-tip: Use POEdit (https://poedit.net/) it can validate the .po file, and helps spotting missing translations etc.

**Comment by swan201** [comment]
@rlf Yeah, I try to Aready use that program. But many format error have in game menu. because korean and english grammer have different location. so I need to test all in game. :) and some colorcode need end color code. So I'm merge and test it. and merge and test it...  haha

I think this request now can merge

**Comment by rlf** [comment]
image

**Comment by swan201** [comment]
@rlf Anything different??

**Comment by swan201** [comment]
@rlf I found Problem

**Pull request closed without merging**
