### PR TITLE
Add support for 1.14 by using inventory management api

### PR DESCRIPTION
**Pull request by Speentie8081**
[InventoryManager v1.1 (dependency)](https://ci.skorrloregaming.com/job/InventoryManager/)

### CODE REVIEW

**Comment by Muspah** [comment]
Hi! Thanks for your (first) PR! All the indentation changes make it a bit hard to read the actual changes to the code. What are you exactly trying to achieve by using a third-party API? Is the external API really adding extra features instead of using the Bukkit/Spigot API directly considering the risk of having to deal with unmaintained code in the future? Thanks!

**Comment by Speentie8081** [comment]
Sorry for the delay I was on a daily bike ride. I also must apologize for the indention changes, I have my intellij settings set to use global tab indention. The api is very simple, it stores the current inventory open in memory with an identifier alongside it. This works around spigot 1.14 no longer having Inventory#getName() and Inventory#getTitle(). [Click here to view the source code for the api](https://github.com/SkorrloreGaming/InventoryManager/blob/master/src/main/java/me/skorrloregaming/InventoryManager.java)

**Comment by ThexXTURBOXx** [comment]
I like the idea behind the InventoryManager, *but*:
There is a better way to get around things:
I think, the main intention behind this PR is, that you can't use the ``Inventory#getTitle`` method anymore, because it was deprecated in 1.13 already and removed in 1.14.
If you want to compare inventories and want to see, if it belongs to your plugin or you want to see, if that inventory is a specific one, this is the "new way" (the way already existed all the time, but nobody really used it yet):
 - Create a custom class, which implements ``InventoryHolder``
 - (Optional) Save any information, you want to save in there
 - When you create an Inventory, pass an instance of the custom made ``InventoryHolder`` as the first parameter
 - When you want to compare Inventories, just check if the ``Inventory#getHolder instanceof CustomInventoryHolder``. If you did the optional step, you can even cast the Holder object to your custom holder then and compare the additional information.

Imo that is way more safe and more like the "1.14 way" to do things.
Maybe I will create a PR today or tomorrow using that technique.

**Comment by Muspah** [comment]
> I'm going to assume you mean for this repository, in which case yes this is my first PR. 
Yes, I was just mentioning the 'First-time contributor' badge next to your name. It's just for this repository ;)

Thanks to both you and ThexXTURBOXx for opening a PR with 1.14 support 😃! I've merge PR #1185 and added a comment there with a bit more information. I'm going to close this PR for now.

**Comment by Speentie8081** [comment]
I understand. It was more of a workaround then a fix.

**Pull request closed without merging**
