### PR TITLE
Update LevelConfig

### PR DESCRIPTION
**Pull request by Muspah**
Trying to find out and update the legacy item names in levelconfig.yml. Some have been renamed, replaced or removed (in favour of metadata, like double slabs). Using MC 1.7.10 to lookup what it is, I can't remember all of them.

Things like DIRT/1 and DIRT/2 (coarse dirt and podzol) are broken already in the current USB builds.

Going to do this in multiple commits, to keep my own history clear until merging.

### CODE REVIEW

**Comment by Muspah** [comment]
HARD_CLAY (TERRACOTTA):
Glazed terracotta is added with the same score (20.0) as regular terracotta. The additional effort to produce glazed is limited (0.1 smelting time).

**Comment by Muspah** [comment]
In legacy Minecraft, WOOD_STEP and WOOD_DOUBLE_STEP were two separate Material types. Both single and double wooden slabs would have a diminishingReturn of 10K. Since MC1.13, they are all counted as WOOD_SLAB (replace wood with wood type). To compensate for this, WOOD_SLAB has a diminishingReturn of 15K now.

**Comment by Muspah** [comment]
Should a wither skeleton skull really give 1000 points?

**Comment by Muspah** [comment]
Why is GLASS 50, but *_STAINED_GLASS 25? 8 stained glass requires 8 glass + 1 dye.

**Comment by marcbal** [comment]
- I suggest putting all the skulls (except wither skull) in the same group. 1000 point is not that much I think, considering this is pretty rare to obtain them (maybe you can add a limit).
- The wither skull is easier to obtain (when you have access to the nether) than the other skull, so a lower score/limit is a good solution.
- I agree the current score for GLASS and STAINED_GLASS are not coherent. Either 25 or 50 for both of them is good for me.
- I would also suggest to reduce the value of SLIME_BLOCK, since it become easily obtainable as long as you find 1 slime chunk. On my server, I reduced it to 50 because the players took advantage of the previous value. Reducing the diminishingReturns may also be a good solution.

Other than that, it looks like the file is fully updated. Is there something else to update?

**Comment by Muspah** [comment]
Thanks for your feedback! Yeah, there are still a few things left, but I wasn't that active the last few weeks.

**Comment by marcbal** [comment]
Hey, I did some work on this, earlier today, but didn’t have time to PR. Maybe you can merge some stuff that I did from this link if you want to save time :)
https://github.com/marcbal/uSkyBlock/commit/73c05d4b3fc71bcdca9dc42b3937eee742abe95f

**Comment by Muspah** [comment]
Sure, will do, thanks!

**Comment by Muspah** [comment]
I'm not sure about the score for shulkerboxes. It's configured to be 500.0 now, but will strongly depend on the server that's running USB because we don't provide a way to get shulker spawns on islands at the moment.

**Comment by Muspah** [comment]
All prismarine blocks have a diminishingReturns value now, considering that prismarine isn't that hard to farm when you have a farm up and running afaik.

**Comment by Muspah** [comment]
I'm not sure about all the diminishingReturns though, it looks fair to limit stones for example to prevent levelling with 500k diorite walls. On the other hand, a 128x128 island contains 4.1M blocks. There should be a way to gain high levels. It all depends on the server imo.

**Comment by Muspah** [comment]
> Hey, I did some work on this, earlier today, but didn’t have time to PR. Maybe you can merge some stuff that I did from this link if you want to save time :)
> [marcbal@73c05d4](https://github.com/marcbal/uSkyBlock/commit/73c05d4b3fc71bcdca9dc42b3937eee742abe95f)

Regarding:
- Merge some wood related stuff together (maybe I could also merge `*_WOOD` and `STRIPPED_*_WOOD` in one place? )

There is one downside to this afaik: the diminishingReturn value will be for all the combined woods.

**Comment by Muspah** [comment]
At least all the legacy materials are out now, and a lot of new blocks are added. It's 3:40AM now, not gonna look into it any further tonight :)

**Comment by Muspah** [comment]
Bumped USB to a new minor release (2.9.0) yesterday, planning on including this change in the following release. Linked to this PR in the release notes on SpigotMC.

**Comment by Muspah** [comment]
Moved to https://github.com/uskyblock/uSkyBlock/pull/21

**Pull request closed without merging**
